### ISSUE TITLE
[1.0] Documentation

### ISSUE THREAD

**Issue by san650** [san650/ember-cli-page-object#115]
API changes a lot from 0.11 to 1.0 and we need to inform users. I think we should:

# Must
- [x] Write documentation for 1.0 features
- [x] Update README.md file
- [x] Remove DOCUMENTATION.md file in favor of using the website
- [x] Update website to have both 0.11 and 1.0 documentation
- [x] Write a complete release notes explaining all the changes
- [x] Migration path

# Nice to have
- [x] Generate API documentation from source code comments (jsdoc)

**Comment by jeradg** [comment]
@san650 @juanazam: Regarding the last outstanding to-do, the migration path from `customHelper` s to descriptors:

@juanazam wrote some good documentation for this here: http://ember-cli-page-object.js.org/docs/v1.1.x/components#customhelper

I think it might be good to make this section more prominent and flesh it out more. Also, rather than featuring it in the `components` page, maybe we should give it its own page.

I think it's a really powerful feature to be able to add your own custom actions, predicates and queries. We could add a short tutorial to help people along.

Thoughts?

**Comment by jeradg** [comment]
Migration guide added in https://github.com/san650/ember-cli-page-object/pull/148.

**Comment by jeradg** [comment]
@san650: Looks like we're done on this issue. Shall we close it?

**Comment by jeradg** [comment]
:clap:
