### ISSUE TITLE
Page contains text

### ISSUE THREAD

**Issue by samselikoff** [san650/ember-cli-page-object#206]
Amazing library!

What's the best way for me to do something like

```js
assert.ok(page.containsText('Foo bar');
```

? I tried

```js
containsText: contains('*')
```

but got the warning about multiple matches, then tried `multiple: true` but that checks that _every_ matched element contains the text. I want to check that _one_ (or more) matched elements contains the text.

**Comment by jeradg** [comment]
@samselikoff: One way I can think of would be to create a collection of all elements containing the text, and make sure that the number of matching elements is correct (or greater than 0).

**Comment by san650** [comment]
@samselikoff @jeradg you can use the `:first` selector to target the whole application.

```js
var page = create({
  scope: ':first'
});

// test
assert.ok(page.contains('foo')); // will work out-of-the-box
```

I'm almost sure this works with the current version of ember-cli-page-object.

Apart from that, I've opened this PR (#209) to add this behavior by default so if no selector is defined then `:first` is used.

```js
var page = create({});

// test
assert.ok(page.contains('foo'));
```

**Comment by san650** [comment]
Just a comment about the auto-generated `contains` property.

There are several properties that are auto-generated for every page object, you can see the list [here](http://ember-cli-page-object.js.org/docs/v1.4.x/components#default-attributes). So just declaring a scope you can use these properties which is nice because it reduces the size of page objects.

An example of this

```js
var page = create({
  scope: '.a-scope',

  foo: {
    scope: '.a-component'
  }
});

// tests
assert.ok(page.contains('lorem ipsum')); // ".a-scope :contains('lorem ipsum')"
assert.ok(page.foo.contains('lorem ipsum')); // ".a-scope .a-component :contains('lorem ipsum')"
```

You can also redefine these methods if you need

```js
var page = create({
  scope: '.a-scope',
  contains: contains('.another-scope')
});

// tests
assert.ok(page.contains('lorem ipsum')); // ".a-scope .another-scope :contains('lorem ipsum')"
```

And lastly you can add a different property if you want to use a more semantic name

```js
var page = create({
  scope: '.a-scope',
  mySemanticProp: contains()
});

// tests
assert.ok(page.mySemanticProp('lorem ipsum')); // ".a-scope :contains('lorem ipsum')"
```

PS: `contains` doesn't actually generate a `:contains` selector, I've used this selector just as an example. You can see the real implementation [here](https://github.com/san650/ember-cli-page-object/blob/dbf823cb01cbeeb115e0b0645168718031e59383/addon/predicates/contains.js#L92).

**Comment by samselikoff** [comment]
Scope is exactly what I needs - thank you!
