### ISSUE TITLE
Undefined error when using mocha's `before`

### ISSUE THREAD

**Issue by SaladFork** [san650/ember-cli-page-object#216]
```js
beforeEach(function() {
  MyPageObject.visit(); // works fine
});

before(function() {
  MyPageObject.visit(); // visit is not defined
});
```

Error is thrown at [visitable.js:95](https://github.com/san650/ember-cli-page-object/blob/v1.4.2/addon/actions/visitable.js#L95).

Using:
  * `ember-cli-page-object@1.4.2`
  * `ember-cli-mocha@0.10.4`
  * `ember-mocha-adapter#0.3.1`
  * `mocha#2.5.3`
  * `chai#3.5.0`

**Comment by san650** [comment]
Thanks for reporting the error, I'll take a look at it.

I don't use mocha with ember a lot, so I'm not too familiar with what changes when calling `before`. What happens if you call `visit('/foo')` from the `before` hook? Does the ember test helper exists?

**Comment by SaladFork** [comment]
Thanks for the quick reply! I'm embarrassed I didn't try the global helper myself, seems an obvious test now.

I'm seeing the same issue with trying to use the global `visit` helper. I suspect now this is not an issue with `ember-cli-page-object`.

Any recommendations as to the right project to report this issue?

**Comment by san650** [comment]
@SaladFork I would say that you should open an issue in [ember-mocha](https://github.com/switchfly/ember-mocha) rather than opening it in [ember-cli-mocha](https://github.com/switchfly/ember-cli-mocha) to ask if this is a expected behavior or not.

Reading about [Mocha's hooks](http://mochajs.org/#hooks) it kind of make sense that these helpers don't exist on the `before` hook. This is because you don't have an _application_ instance yet when this hook is executed but you do have one when `beforeEach` runs.

Remember that when an application is instantiated, it registers all the test helpers in the global context (in the _window_ object).

**Comment by SaladFork** [comment]
Thanks @san650! Unless I'm misunderstanding, a common pattern in Mocha is to nest `describe`/`context` blocks and use `before`/`beforeEach` in nested ones in which case the application would be initialized. For example:
```js
describe('Some acceptance test', function() {
  let application;

  beforeEach(function() {
    application = startApp();
  });

  afterEach(function() {
    destroyApp(application);
  });

  context('On the main page', function() {
    beforeEach(function() {
      MainPageObject.visit();
    });

    it('should have some value on the page', function() {
      // ...
    });

    it('should have another value on the page', function() {
      // ...
    });
  });
});
```

Thanks again!

**Comment by Turbo87** [comment]
@SaladFork Indeed I think you're misunderstanding. The `beforeEach()` block in your example will still be executed twice, once for each test. In fact the nested `before()` block will be executed *before* the outer `beforeEach()` block.

I've taken your example and put some `console.log()` calls inside those blocks and this is the output:

```
  Some acceptance test
    The main page
before
beforeEach
      ✓ should have some value on the page
beforeEach
      ✓ should have another value on the page
```
