### ISSUE TITLE
Resetting test container

### ISSUE THREAD

**Issue by brancusi** [san650/ember-cli-page-object#219]
Hi,

This issue is somewhat of a [duplicate of 132](https://github.com/san650/ember-cli-page-object/issues/132). I am using ember-modal-dialog and it uses ember-worm-hole.

The element that I'm trying to select ends up being outside of the test container and in the body instead.

Was there ever a solution for resetting to a specific container, the last issue said the discussion should continue on slack.

Thanks

**Comment by san650** [comment]
@brancusi since v1.3.0 there's an option in every page object helper to set a different container.

```js
var page = create({
  text: text('.a-selector', { testContainer: 'body' })
});
```

This way when you call `page.text`, the page object will search `.a-selector` inside the body instead of the testing container.

See `New testContainer option` in  https://github.com/san650/ember-cli-page-object/releases/tag/v1.3.0 

@brancusi Is this what you need? Please, let me know how it goes!

**Comment by san650** [comment]
Hi @brancusi are you still having issues with this? Did you tried the solution I shared in my previous message?

**Comment by brancusi** [comment]
HI @san650, we are going to try this now. Sorry for the delay in getting back.

Thank you for the feedback.

Will keep you posted.

**Comment by brancusi** [comment]
Hi @san650, the test container works, but I still have an issue, most likely nothing to do with page-object, but thought I would ask in case you have a solution.

Basically, it seems that when I have an interactive element mounted into something via wormhole, i.e. a popup menu with some menu buttons, they are somehow all disconnected from their bound actions. In this case, clicking those menu items inside `body>wormhole>div>button`, never trigger the action.

This only happens in the tests though, in the running app they trigger correctly. Any thoughts?

**Comment by san650** [comment]
If there's nothing odd in the actions it should be working fine I think. Let me try to reproduce this error in an ember-twiddle to understand what's happening.

Personally, having the page objects to play nicely with ember-wormhold is a priority because lot's of people are using it -- it's a very common pattern -- so let's track all the issues!

I'll keep this issue updated with my findings, I'll try to spend some time on it between today and tomorrow.

@brancusi if the app you're working is open source or you have a twiddle that I can take a look at which reproduces the issue, would be great also!

**Comment by san650** [comment]
@brancusi just a quick question, the tests in question are acceptance tests or component integrations tests?

**Comment by san650** [comment]
@brancusi please feel free to open the issue again if you're still experiencing problems with this.
