### ISSUE TITLE
isVisible when working with collections expects scope

### ISSUE THREAD

**Issue by henryw14** [san650/ember-cli-page-object#341]
I have a page object 
```
{
  scope: ".top-level"
  errorMessages: collection({
    itemScope: "[data-test='error-message']"
  })
}
```
Then I go to use, in a context when no error messages are visible: `page.errorMessages().isVisible` which returns true.

The created selector in the find in the is-visible.js is only `".top-level"` which returns an element and that element is visible (aka has no care for my items)

Which really leads to the question: is this the expected behavior? I would have expected this to be true if all items were visible and false otherwise

**Comment by san650** [comment]
`page.errorMessages().isVisible` checks that the element `.top-level` exists. That's because you didn't select any child item, so it checks for the "container".

To check if a specific element is visible, you have to do `page.errorMessages(0).isVisible`.

If you want to check how many children are rendered in the page (visible or not) you can do `page.errorMessages().count`.

> I would have expected this to be true if all items were visible and false otherwise
That would be really cool but it doesn't do this.

You can do something like
`page.errorMessages().toArray().every(e => e.isVisible)`

I'll close the issue but feel free to open it again if you need more info.
