### ISSUE TITLE
`getter` as component `scope`

### ISSUE THREAD

**Issue by oliverlangan** [san650/ember-cli-page-object#407]
(Page Object) Components are a great way to create reusable test helpers for (Ember) components. In some cases, it the requirements for choosing a specific element are more complicated than a simple selector string.

Take the case of selecting an element by its label. Sometimes the element is inside the label, but often the relationship is by ID, via the `for` attribute. And both may be within another element, which is the proper 'top' of a component.

This type of lookup is possible with a `getter`, but elements looked up in this way do not behave as `component`s: they can not have additional behaviors added to them.

**Comment by ro0gr** [comment]
@oliverlangan not sure I understand the issue. Can you please share an example of how do you want a `getter` to behave?

**Comment by oliverlangan** [comment]
Sure... this is pseudocode, but I would like to have something like:

```
let fieldLabeledFoo = PageObject.create({
  // labels may point to objects outside of their tree
  scope: getter(function () { // or `scope() { ... }`
    let $label = findElement(this, 'label:contains("foo")');
    let id = $label.attr('for')
    return getElementById(id);
  }),

  // we can now attach additional functionality to the found object
  placeholder: attribute('placeholder')
});
```

use it like:
```
assert.equal(fieldLabeledFoo.placeholder, 'expected value');
```

Since I can already return objects, which will then be treated as page object components, I could then wrap this in a function (not shown here) which takes an arbitrary label string, but is still not resolved until I call it.

```
let page = {
  visitable(...),
  fooField: fieldLabeled('foo'),
  ...
}
```

I do have something a bit like this working, but since the scope can not be resolved dynamically it requires that the page already be loaded before the page object is defined.

**Comment by ro0gr** [comment]
I see what you are doing. I think this is not possible due to `findElement` [tries](https://github.com/san650/ember-cli-page-object/blob/ea4bd566089c4ee7f3e5c9a1e629279e3b4ea736/addon-test-support/-private/execution_context/rfc268.js#L147) to calculate the whole page-object node's scope. This makes findElement to recursively call `this.scope` and leads to infinite recursion :disappointed:

**Comment by ro0gr** [comment]
But it should be theoretically possible to:
```
import Ceibo from 'ceibo';

scope: getter(function () { // or `scope() { ... }`
    let $label = findElement(Ceibo.parent(this), 'label:contains("foo")');
```

**Comment by ro0gr** [comment]
Seems like I have a working snippet:

```js
let fieldLabeled = function(name: string) {
  return {
    scope: getter(function (this: any) { // or `scope() { ... }`
      let labelSelector = buildSelector(Ceibo.parent(this), `label:contains("${name}")`, {});
      let $label = $(labelSelector);

      return $label.attr('for') ? `#${$label.attr('for')}` : `${labelSelector} input`;
    }),

    placeholder: attribute('placeholder')
  }
};
``` 

Here are 2 important points to note:
  - Eager creation of Page Object components should be avoided. `create` enumerates each passed objects's property recursively. So the problem appears when the top level `create` accesses a getter which is already set up by the first `create`:
```
  create({
    myComponent: create({
      // it's executed because of top-level `create`
      someProp: fieldLabeled('label text')
    })
  })
``` 
  - A circular reference on `this.scope` should be avoided. Seems like the best bet is to pass a parent node for the full selector calculation 

Closing this since it looks like the feature is supported :laughing:
