### ISSUE TITLE
When will beta be released?

### ISSUE THREAD

**Issue by sukima** [san650/ember-cli-page-object#434]
I've noticed a common thread in the Discord when talking about page-objects in that there are two distinct answered depending if someone is using the beta or not. This is often followed up with a comment about this repo being in beta for a very long time.

Some teams are uncomfortable using beta versions in their production apps.

What are the blockers to getting this over the hump and into a new version? The community has been testing it for quite some time&mdash;I'm sure; considering the first beta was released February 23, 2018 (9 months ago).

**Comment by san650** [comment]
@sukima I think we need a thumbs up from people using the beta and saying it's ok to release it. The other bulk of work was updating the documentation to reflect how to use this version instead of the old one.

Maybe @ro0gr is the person with more info about current state of the beta and if we're ready to release it.

My 2¢ is: Let's release it, if we're afraid of regressions, let's release it as a new major version so people can opt-in into updating.

**Comment by san650** [comment]
Also, I've been really away from the project for the last year and a half (and away from Ember) so I don't think I have enough insight of what's happening in Ember world lately that could block this version from being released.

I would love to transfer the project to people that is more involved with Ember and the development of this addon. @ro0gr, @sukima?

**Comment by juanazam** [comment]
@san650 @sukima @ro0gr I'm upgrading an app to 3.x and beta seems to be working well with the new testing layout.

I can help with that is pending with the docs (not sure what's the state on that)

**Comment by ro0gr** [comment]
First of all, sorry guys for letting release to hang for so long!

> The community has been testing it for quite some time

Yes. I believe there are no known issues with the current beta from the implementation standpoint. And we could probably have it released already. However I feel like promoting a new release without documentation being updated is not a right thing to do.

Initially [I've thought](https://github.com/san650/ember-cli-page-object/pull/357#issuecomment-354991717) that documentation can stay unchanged. I was wrong. 

I believe that with the new test helpers support in the guides we have to recommend usage of `async`/`await` exclusively. My first naive attempts to re-write examples to just use the new syntax have shown me that most of examples just loses their sense because of simplification/unification of ember testing APIs. This led me to a conclusion that some parts of documentation has to be completelly re-written. Unfortunatelly updating docs took me much longer than I've expected. 

> let's release it as a new major version so people can opt-in into updating.

I think we can safely release it as a minor release cause there are no expected breakages in API.

> this repo being in beta for a very long time.

ok, in the end I totally get the pain about the current state of things. Let's release it by Monday despite the state of the docs. I'll do my best to improve the docs as much as I can until then. Any help is much appreciated.

> I can help with that is pending with the docs (not sure what's the state on that)

There is a Quickstart page PR https://github.com/san650/ember-cli-page-object/pull/431 which I think is pretty close to what we need. Currently I'm working on a components page update. Also some of the  work(migrate to `async/await` and dedicated `moduleFor` page) is not shared in any PR yet. Going to share it soon.

**Comment by san650** [comment]
> Let's release it by Monday

🎉 👏 💯 

>I'll do my best to improve the docs as much as I can until then. Any help is much appreciated.

@ro0gr I can try to help on this on Saturday (I'll try to free some time to help with this problem). Do you have a list of what's most important to rewrite?

**Comment by ro0gr** [comment]
@san650 I've just summarized the most critical(in my opinion) parts in a separate issue https://github.com/san650/ember-cli-page-object/issues/436. I think the components page is the last difficult part of the puzle. I have some progress locally, but I'm not satisfied with what I have yet..

**Comment by ro0gr** [comment]
it's finally released! Thank you all 🖐
