### ISSUE TITLE
ENHANCEMENT - `setupPageComponentTest` for hooks with easier setup with test APIs

### ISSUE THREAD

**Issue by rtablada** [san650/ember-cli-page-object#444]
Just a suggestion in our app we have started using a hook helper function (in QUnit tests) like this:

```
export function setupPageComponentTest (hooks, page) {
  hooks.beforeEach(function() {
    page.setContext(this);
  });

  hooks.afterEach(() => {
    page.removeContext();
  });
}
```

This removes a lot of boilerplate from our component tests since we don't need to set the context and remove context for component tests using EPO.

I'm not sure if this is something other teams would value?

The one worry I have (and why I did not create a PR yet) is that this helper is coupled to `ember-qunit`...

**Comment by san650** [comment]
I think it makes sense to include it in the package. Can you create a PR?

**Comment by rtablada** [comment]
Yeah I'll make a PR and some docs on how to use ECPO in integration tests for components.

**Comment by ro0gr** [comment]
Hi, there is actually a PR already for that https://github.com/san650/ember-cli-page-object/pull/432

**Comment by ro0gr** [comment]
As far as I understand this helper is supposed to enable `moduleForComponent` mode for the page object. Is it correct or do you need it in the `setupRenderingTest` for some reason?

I think a test helper for a specific page object is a bad path to go. What if the test needs few page objects to use? The relevant test setup would look something like:

```js
  setupPageComponentTest(hooks, page1);
  setupPageComponentTest(hooks, page2);
```
which doesn't look good to me, since we never want different test modes within the same test.

I mean that the test mode seems like a global state within a test to me. But we currently store and read it from the [specific pageObject instance](https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/-private/execution_context.js#L27). I think with the new test helper we can do better, by setting a test mode globally and then take care to clean it up in `afterEach`, so we don't need to pass a page object instance to it:

```js
  setupPageObjects(hooks, {
    moduleForComponent: true
  })
``` 
I think it's even possible to do it in a backward compat way(supporting `setContext` as a fallback)

Hope it makes sense and sorry for quite confusing thoughts dump(a bit under preassure now)...

**Comment by bendemboski** [comment]
My 2 cents: https://github.com/san650/ember-cli-page-object/pull/432#issuecomment-461577885
