### ISSUE TITLE
Allow to access parent component in custom helpers

### ISSUE THREAD

**Issue by irnc** [san650/ember-cli-page-object#45]
Currently `build` function receives `parent` but does not uses it at all.

See https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/build.js#L52

What do you think about allowing custom helpers to access parent from component object, e.g. put `parent` as a `component` property at `build` step and pass it in `options` at `buildPageObjectAttribute` step.

If there is no major objection, I will prepare pull request with implementation and example which implements custom attribute on collection component and reuses `item` component from it.

**Comment by san650** [comment]
This sounds great!

When I was first creating the addon I wanted to have the parent available so we could create nice error messages when `findWithAssert` helper fails to find an element. 

i.e. given...

```
andThen(function() {
  assert.equal(page.users().count(), 10);
  assert.equal(page.users(1).firstName(), 'John');
});
```
As of today, if any of those look ups fail because the elements doesn't exist on the page, we see an error that reads something like

```
Error: Element table.users tr:nth-of-type(1) span not found.
```

We actually have all the information to create better error messages, we could show the user an error message like

```
The property "page.users[1].firstName" with selector "table.users tr:nth-of-type(1) span" doesn't match with an element.
```

or something similar (I am sorry for my English!)

Another ideas is to be able to turn on a debug configuration flag so every time a page object attribute is resolved the full qualified path of the attribute plus the associated selector is printed on the console. This could be a great tool to debug deep nested page objects components.

The idea is to print something similar to:

```
attribute: page.users[1].firstName
  > selector: table.users tr:nth-of-type(1) span
```

I know all this has nothing to do with what you are asking here but I wanted to give you the big picture of why we are receiving the `parent` parameter on `build` function.

Please, let me know if you need help implementing what you suggested, I think it's a really good idea. Also let me know what do you think about these error/debugging ideas (and if you want to help us implementing them).

**Comment by jeradg** [comment]
@irnc: In ember-cli-page-object v1.x, you can now access a node's parent inside a custom descriptor using `Ceibo.parent(this)`.

For example, the `getRoot()` helper uses `Ceibo.parent()` to walk up the page object tree to find the page's root node: https://github.com/san650/ember-cli-page-object/blob/2421e884b71f6e74e66eb4d8754f8456e088297e/test-support/page-object/helpers.js#L235

So if you needed to create a descriptor that has access to its parent, you can do something like:

```js
import Ceibo from 'ceibo';

export function doSomethingWithParent(selector, options = {}) {
  return {
    isDescriptor: true,

    value() {
      const parent = Ceibo.parent(this);

      // ...do something with the parent node

      return this;
    }
  };
}
```

(Side note: Ceibo is a small library that ember-cli-page-object uses to parse the page-object tree.)

Hope that helps!

(cc @san650)
