### ISSUE TITLE
Using this library without using Ember - still possible?

### ISSUE THREAD

**Issue by schickm** [san650/ember-cli-page-object#480]
Hey there,

At a previous job I worked in Ember and loved using this library.  At my current job we're using something different.  But, we are doing acceptance testing via Webdriver.io. I noticed that the homepage says:

> Agnostic to the testing framework (but really hooked on Ember!)

Does anybody feel like this is feasible? If so, any pointers as to how to use this library as as standalone npm module seperate from ember?...Or am I better off using the underlying [ceibo](https://github.com/san650/ceibo) library to try and build my own direct integration with Webdrive.io?

Thanks for the great library, and if I don't hear back, I'll probably just start digging in to ceibo.

**Comment by ro0gr** [comment]
Yeah, that's something we'd love to support.

Unfortunatelly, at the moment, it doesn't seem feasible to achieve it w/o some refactorings on ec-page-object side.

For example, introducing of adapters(#479) would allow us to start experimentation on that front in user land.

Also at the moment we depend on some "@ember/**" imports, which do not have a standalone packages in npm:
 - '@ember/error'
 - '@ember/application/deprecations'
 - '@ember/polyfills'
 - '@ember/array'
 - '@ember/debug'
 - '@ember/object'
 - '@ember/utils'

We have to figure out a strategy for each of this packages.

The last blocker in my mind is a dependency on ember-cli build pipeline, we currently do some magic with merging of "jquery", which should be fleshed out as well, in order to make ec-page-object work cross-framework'y.

**Comment by schickm** [comment]
Yeah, I can see how introducing something like adapters would be a big step towards that.  

Ember: there's so much great stuff to integrate with...but once you do, you are married to Ember.  Not a bad thing - just "a thing".

Thanks for the fast response and explanation!  It looks like I'll just look into rolling my own ontop of ceibo then.

**Comment by ro0gr** [comment]
Most of the deps listed above are not hard requirements for a proper integration. I think we should just get rid of them.

Good luck!
