### ISSUE TITLE
Accidental breaking change? tests started failing when going from 1.16 to 1.17

### ISSUE THREAD

**Issue by NullVoxPopuli** [san650/ember-cli-page-object#496]
https://github.com/NullVoxPopuli/emberclear/pull/660/checks?check_run_id=556759684

Looks like it relates to disabled state.

**Comment by ro0gr** [comment]
Ya, thanks for the report!

it was introduced by https://github.com/san650/ember-cli-page-object/commit/873e1cda4a12a7642439a943bc4d7d755aec3ae9#diff-0dc38de04449789b2e0f2463693cb62cR88

prior to the change we've used `$(element).attr(attributeName)`, and now switched to `element.getAttribute(`. It turns out jQuery normalizes attributes. So we have to restore to use it for `attribute`.

Also I've noticed the `multiple` deprecation, which doesn't look legit. Just haven't had time to look into it yet.

sorry for inconveniences.
