### ISSUE TITLE
Deprecation calls need to be updated for compat with Ember 3.24

### ISSUE THREAD

**Issue by NullVoxPopuli** [san650/ember-cli-page-object#525]
These errors are triggered before deprecation-workflow can intercept them
```
Error: When calling `deprecate` you must provide `for` in options. Missing options.for in "ember-cli-page-object.old-collection-api" deprecation
Error: When calling `deprecate` you must provide `since` in options. Missing options.since in "ember-cli-page-object.old-collection-api" deprecation
Error: When calling `deprecate` you must provide `for` in options. Missing options.for in "ember-cli-page-object.create-url-argument" deprecation
Error: When calling `deprecate` you must provide `since` in options. Missing options.since in "ember-cli-page-object.create-url-argument" deprecation
Error: When calling `deprecate` you must provide `for` in options. Missing options.for in "ember-cli-page-object.string-properties-on-definition" deprecation
Error: When calling `deprecate` you must provide `since` in options. Missing options.since in "ember-cli-page-object.string-properties-on-definition" deprecation
```

Scratch that, these are being thrown from `ember-source` deprecations: `ember-source.deprecation-without-for`
and I have `throwOnUnhandled: true` in deprecation workflow.

**Comment by ro0gr** [comment]
According to the https://github.com/san650/ember-cli-page-object/issues/512, I think we should replace `deprecate` coming from the '@ember/application/deprecations', with our home grown `deprecate` util(or some 3rd party standalone util). It may also support the `for` field. I think this should be done for both v1 and v2, since there should be no other blockers to use v1 with the latest version of ember.

**Comment by ro0gr** [comment]
Alright, I just realized it's not about the point when deprecations are being fired, it's about any time ember's `deprecate(` is invoked... I'll take a look at it.
