### ISSUE TITLE
zero-indexing of collections?

### ISSUE THREAD

**Issue by bantic** [san650/ember-cli-page-object#58]
Is there a specific reason that the items in a collection are indexed starting at 1 and not 0? It was somewhat surprising to realize that I needed to use `page.someCollection(1)`  to get the first object (and that `page.someCollection(0)` returned the entire collection rather than an individual item). Would you accept a PR that changed [`scopeWithIndex`](https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/collection.js#L15-L17) and the [collection method](https://github.com/san650/ember-cli-page-object/blob/master/test-support/page-object/collection.js#L59) to accept `0` to get the first item?

**Comment by juanazam** [comment]
@bantic Thanks for comment!

Your are right! We are aware of this, this happens because of the how we started implementing collections in the beginning. We used the `nth-of-type` selector to search for items on a collection, and that selector is 1-based. Right now we are not using it, but we don't want to change the current implementation because it would break compatibility with projects which rely on this behavior.

One thing that may be useful is to throw an error when someone tries to use collections with 0.
In that case we can throw an error like: `new Error("Collections are 1-based arrays")` so we prevent users from falling into this case.

thoughts?

**Comment by bantic** [comment]
@juanazam Yeah, good idea! I'll issue a PR. I would also cast a vote for considering a breaking change to the indexing for the next major revision of this add-on.

Perhaps a path forward would be to add a deprecation when accessing an indexed item in a collection: "Accessing items in a collection is 1-based but will change to 0-based in version X". Consumers could set a flag in their test config like `USE_ZERO_BASED_COLLECTIONS:true` that would both silence the deprecation and change the behavior to use zero-based indexes. Then in the next major revision drop the deprecation and the 1-based behavior. I understand if that's a bigger change than you'd want to make, though. It just seemed quite surprising that the collection didn't use zero-based indexing.

Thanks for making this! It's a great library.

**Comment by juanazam** [comment]
@bantic we are considering deprecating this behavior in the future, and in case we decide to, your suggestions sounds great!

Thanks for using it and helping us making it even better
