### ISSUE TITLE
is there a way to create recursive page object?

### ISSUE THREAD

**Issue by ollar** [san650/ember-cli-page-object#600]
Hello. I am making a component which is basically a list with some lists included and they are made with the same component :) I am just interesting is there a way to create a PO like:

```
component: {
  scope: '[data-test-component]',
  ...someChecks,
  get subComponent() {
    return component;
  }
}
```
so I can use someChecks on subComponent also?

**Comment by ro0gr** [comment]
Hey. Great question! AFAIK, currently there is no really good way to achieve it. However, it's totally possible to achieve in few ways. 

The way I do currently approach it for one old tree component is totally public but a bit dirty. The idea there is to limit the recursion depth when creating children components beforehand. Though it does the job perfectly it does not feel good implementation wise due to eagerness, so I'll ignore to consider this approach for now.

Instead, I'd explore a lazy way using getters like you are going to do in your example.

Let's assume the following markup:
```html
<ul class="root">
  <li>
    <div>1</div>
  </li>
  <li>
      <div>2</div>
      <ul>
          <li>
            <div>2.1</div>
          </li>
      </ul>
  </li>
  <li>
    <div>3</div>
  </li>
</ul>
```
Here nested lists(`> ul`) are defined inside `li`s, alongside with the direct `li` content, so in order to properly distinct between nested lists and "direct content" we namespace it with `<div>`.

That's how we could define it with page objects:
```ts
/* used TS here out of curiosity. If you don't really need it hope it won't be an issue to reduce down to JS*/

/* avoid circullar dependency types issue */
type List = {
  scope: string;
  items: Collection<ReturnType<typeof Item>>;
}

function List(scope: string): List {
  return {
    scope,
    items: collection('> li', Item(''))
  }
}

function Item(scope: string) {
  return {
    scope,

    text: text('> div'),

    get list() {
      return create(
        List('> ul'),

        // This is not a part of recommended public API, though it is a public in fact.
        // no public typings for it.
        // @ts-expect-error
        { parent: this },
      )
    },
  }
}
```
To make it clear, I've never used this approach. But I can't see a reason why it'd fail to work. Here is how it can be used in tests:
```ts
assert.strictEqual(myList.items.length, 3);

assert.deepEqual(myList.items.map((i) => {
  return i.text;
}), ['1', '2', '3']);

assert.deepEqual(myList.items[0].list.items.map((i) => {
  return i.text;
}), []);

assert.deepEqual(myList.items[1].list.items.map((i) => {
  return i.text;
}), ['2.1']);
```

hope it would help!

**Comment by ollar** [comment]
thanks, @ro0gr! I didn't check this solution yet but it looks good!
