### ISSUE TITLE
All imports must be declared as dependencies or peers

### ISSUE THREAD

**Issue by NullVoxPopuli** [san650/ember-cli-page-object#605]
Looking at https://github.com/san650/ember-cli-page-object/blob/master/package.json#L41

There are no mentions of `@ember/test-helpers`, used here: https://github.com/san650/ember-cli-page-object/blob/master/addon-test-support/-private/compatibility.js#L43
(also, this directly uses requirejs, which will not be vite-compatible -- highly recommend using normal imports)

**Comment by ro0gr** [comment]
> also, this directly uses requirejs, which will not be vite-compatible -- highly recommend using normal imports

I think normal imports is no-go for v1, since it's supposed to support old `ember-test-helpers`, `ember-cli-qunit` etc,.. so we need a way of non-static import there.

The good news is that in v2-beta we should be `requirejs`-free https://github.com/san650/ember-cli-page-object/blob/7e92a377cbcbfcad1f980bc7c713c062bc321c8a/addon/src/adapters/rfc268.js#L1-L11
and we should be peer dependencies friendly as well https://github.com/san650/ember-cli-page-object/blob/7e92a377cbcbfcad1f980bc7c713c062bc321c8a/addon/package.json#L74-L82

**Comment by NullVoxPopuli** [comment]
Oh cool, when's that being released?

**Comment by ro0gr** [comment]
it's published as beta(https://github.com/san650/ember-cli-page-object/releases/tag/v2.0.0-beta.5) for now. I wish it were released as stable, however can't provide you with a promise on exact timing. There is some work to be finished still, and I have some obstacles preventing me to focus on it properly at the moment. 

BTW, I believe beta is quite stable actually. It's beta mostly because we need to finish cleaning up few remaining deprecations and finish some internal refactoring, which potentially could have some minor breaking changes.
